environment:
  ci_type: ci_unit
  matrix:
    - nodejs_version: 6
      TEST_CASSANDRA_VERSION: 3.0.6
      ci_type: ci
    - nodejs_version: 5
    - nodejs_version: 4
    - nodejs_version: 0.12
    - nodejs_version: 0.10
platform:
  - x64
install:
  - ps: .\appveyor.ps1
  - npm install
build: off
cache:
  - node_modules -> package.json
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\deps -> appveyor.ps1
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
